### ISSUE TITLE
GeneralScript

### ISSUE THREAD

**Issue by jayleetx** [ds-elections/rcv-in-sf#3]
@mialeung @MYancheff please help I can't figure out what's wrong with the GeneralScript.R file.

I keep getting an `error: subscript out of bounds` but I haven't been able to access where the error is, nor can I find it through manual inspection. I'm pretty sure it's in the i loop, because the j part at the top is working fine. So far I've just been comparing it to the loop_attempt_2.R file (which works) to see if I can find the error by hand.

**Comment by mialeung** [comment]
I'll look at now, and if I can't figure it out, I can bring it to Chester tomorrow @jayleetx
